# Generated by Django 4.0.4 on 2022-06-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_modelform1_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelform1',
            name='Diagnosis',
        ),
        migrations.RemoveField(
            model_name='modelform1',
            name='department',
        ),
        migrations.RemoveField(
            model_name='modelform1',
            name='drdep',
        ),
        migrations.RemoveField(
            model_name='modelform2',
            name='address',
        ),
        migrations.RemoveField(
            model_name='modelform2',
            name='age',
        ),
        migrations.RemoveField(
            model_name='modelform2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelform2',
            name='roomNumber',
        ),
        migrations.AddField(
            model_name='modelform1',
            name='exitDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='modelform2',
            name='forigenKey',
            field=models.ForeignKey(default='30', on_delete=django.db.models.deletion.CASCADE, related_name='from2form', to='forms.modelform1'),
        ),
        migrations.AlterField(
            model_name='modelform2',
            name='drdep',
            field=models.CharField(max_length=100),
        ),
    ]
