# Generated by Django 4.0.4 on 2022-06-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_modelform1_exitdate_modelform1_nationalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelform1',
            name='exitDate',
            field=models.DateTimeField(null=True),
        ),
    ]
