# Generated by Django 4.0.4 on 2022-06-28 11:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0006_alter_modelform1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform1',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 13, 25, 27, 436637), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='modelform2',
            name='forigenKey',
            field=models.ForeignKey(default='30', on_delete=django.db.models.deletion.CASCADE, related_name='form2form', to='forms.modelform1'),
        ),
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationalId', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMAL')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
